************************* 80 columns *******************************************
***
*** --------------------------------------------------------------------
*** Pathway Logic Assistant.
*** Copyright (C) 2006, SRI International.  All Rights Reserved.
***
*** This program is free software; you can redistribute it and/or
*** modify it under the terms of the GNU General Public License
*** as published by the Free Software Foundation; either version 2
*** of the License, or (at your option) any later version.
***
*** This program is distributed in the hope that it will be useful,
*** but WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*** GNU General Public License for more details.
***
*** You should have received a copy of the GNU General Public License
*** along with this program; if not, write to the Free Software
*** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*** --------------------------------------------------------------------
***

***
***  components.maude
*** 
*************************************************************************

fmod PROTEINOPS is inc DISH .
**** inc DOMAIN .

*************************************************************************

sort ErbB1L .    *** ErbB1 Ligand
subsort ErbB1L < Protein .

op 1433x1 : -> Protein . *** the 1433 protein(s) that bind to Raf1

op Cbl : -> Protein [metadata "(\
  (spname CBL_HUMAN)\
  (spnumber P22681)\
  (hugosym CBL)\
  (synonyms \"CBL E3 ubiquitin protein ligase \" \
            \"Signal transduction protein CBL \" \
            \"Proto-oncogene c-CBL \" \
            \"Casitas B-lineage lymphoma proto-oncogene \" \
            \"CBL2 \"))"] .

op DAG : -> Chemical [metadata "(\
   (category Chemical)\
   (keggcpd C00165)\
   (synonyms \"Diacylglycerol \" ))"] .

op Egf : -> ErbB1L [metadata "(\
  (spname EGF_HUMAN)\
  (spnumber P01133)\
  (hugosym EGF)\
  (category Ligand)\
  (synonyms \"Pro-epidermal growth factor precursor, EGF\" \
            \"Contains: Epidermal growth factor, Urogastrone \"))"] .

op EgfR : -> Protein [metadata "(\
  (spname EGFR_HUMAN)\
  (spnumber P00533)\
  (hugosym EGFR)\
  (category Receptor)\
  (synonyms \"Epidermal growth factor receptor precursor\" \
            \"Receptor tyrosine-protein kinase ErbB-1, ERBB1 \"))"] .

op ErbB2 : -> Protein [metadata "(\
  (spname ERB2_HUMAN)\
  (spnumber P04626)\
  (hugosym ERBB2)\
  (category Receptor)\
  (synonyms \"Receptor tyrosine-protein kinase erbB-2 precursor\" \
            \"p185erbB2, C-erbB-2 \" \
            \"NEU proto-oncogene \" \
            \"Tyrosine kinase-type cell surface receptor HER2 \" \
            \"MLN 19, HER2, NEU, NGL, TKR1 \"))"] .

op Gab1   : -> Protein [metadata "(\
  (spname GABI_HUMAN)\
  (spnumber Q13480)\
  (hugosym GAB1)\
  (synonyms \"GRB2-associated binding protein 1 \" \
            \"GRB2-associated binder-1 \"))"] .

op Grb2 : -> Protein [metadata "(\
  (spname GRB2_HUMAN)\
  (spnumber P62993)\
  (hugosym GRB2)\
  (synonyms \"Growth factor receptor-bound protein 2\" \
            \"GRB2 adapter protein \" \
            \"SH2/SH3 adapter GRB2 \" \
            \"Abundant Src homology protein, Ash protein, Ash \"))"] .

op Hras : -> Protein [metadata "(\
  (spname RASH_HUMAN)\
  (spnumber P01112)\
  (hugosym HRAS)\
  (synonyms \"Transforming protein p21/H-Ras-1 c-H-ras\" \
            \"HRAS1 \"))"] .

op IP3 : -> Chemical [metadata "(\
   (category Chemical)\
   (keggcpd C04569)\
   (synonyms \"Inositol-1,4,5-triphosphate \" ))"] .

op Pak1 : -> Protein [metadata "((ssloc  )\
  (spnumber Q13153)\
  (hugosym PAK1)\
  (synonyms \"Serine/threonine-protein kinase PAK 1\"\
            \"p21-activated kinase 1 \"\
            \"PAK-1, P65-PAK, Alpha-PAK \"\
            \"PAK1_HUMAN \"))"] .

op Pi3k : -> Composite . ***(
  consists of a catalytic subunit and a regulatory subunit
  op Pik3ca : -> Protein [metadata "(\
  (spname PK3CA_HUMAN)\
  (spnumber P42336)\
  (hugosym PIK3CA)\
  (EC 2.7.1.153)\
  (synonyms \"Phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic \" \
            \"subunit, alpha isoform \" \
            \"PI3-kinase p110 subunit alpha \" \
            \"PtdIns-3-kinase p110, Pi3k \"))"] .
  op Pik3cb : -> Protein [metadata "(\
  (spname PK3CB_HUMAN)\
  (spnumber P42338)\
  (hugosym PIK3CB)\
  (EC 2.7.1.153)\
  (synonyms \"Phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic \" \
            \" subunit, beta isoform \" \
            \"PI3-kinase p110 subunit beta \" \
            \"PtdIns-3-kinase p110, Pi3k, Pi3kbeta \"))"] .
  op Pik3cd : -> Protein [metadata "(\
  (spname PK3CD_HUMAN)\
  (spnumber O00329)\
  (hugosym PIK3CD)\
  (EC 2.7.1.153)\
  (synonyms \"Phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic \" \
            \"subunit delta isoform \" \
            \"PI3-kinase p110 subunit delta \" \
            \"PtdIns-3-kinase p110, Pi3k, p110delta \"))"] .
  op Pik3cg : -> Protein [metadata "(\
  (spname PK3CG_HUMAN)\
  (spnumber P48736)\
  (hugosym PIK3CG)\
  (EC 2.7.1.153)\
  (synonyms \"Phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic \" \
            \"subunit, gamma isoform \" \
            \"PI3-kinase p110 subunit gamma \" \
            \"PtdIns-3-kinase p110, Pi3k, Pi3kgamma \"))"] .
  op Pik3c3 : -> Protein [metadata "(\
  (spname Q15134_HUMAN)\
  (spnumber Q15134)\
  (hugosym PIK3C3)\
  (synonyms \"Phosphatidylinositol 3-kinase \" \
            \"hVPS34 \"))"] .
  op Pik3r1 : -> Protein [metadata "(\
  (spname P85A_HUMAN)\
  (spnumber P27986)\
  (hugosym PIK3R1)\
  (synonyms \"Phosphatidylinositol 3-kinase regulatory alpha subunit \" \
            \"PI3-kinase p85-alpha subunit \" \
            \"PtdIns-3-kinase p85-alpha, Pi3k, GRB1 \"))"] .
  op Pik3r2 : -> Protein [metadata "(\
  (spname P85B_HUMAN)\
  (spnumber O00459)\
  (hugosym PIK3R2)\
  (synonyms \"Phosphatidylinositol 3-kinase regulatory beta subunit \" \
            \"PI3-kinase p85-beta subunit \" \
            \"PtdIns-3-kinase p85-beta \"))"] .
  op Pik3r3 : -> Protein [metadata "(\
  (spname P55G_HUMAN)\
  (spnumber Q92569)\
  (hugosym PIK3R3)\
  (synonyms \"Phosphatidylinositol 3-kinase regulatory gamma subunit \" \
            \"PI3-kinase p85-gamma subunit \" \
            \"PtdIns-3-kinase p85-gamma, p55PIK \"))"] . )***

op PIP2 : -> Chemical [metadata "(\
   (category Chemical)\
   (keggcpd C04569)\
   (synonyms \"Phosphatidylinositol-4,5P \" ))"] .

op PIP3 : -> Chemical  [metadata "(\
   (category Chemical)\
   (keggcpd C05981)\
   (synonyms \"Phosphatidylinositol-3,4,5P \" ))"] .

sort Plc .
subsort Plc < Protein .

op Plcg : -> Plc .  *** Family
  op Plcg1 : -> Protein [metadata "(\
  (spname PIG1_HUMAN)\
  (spnumber P19174)\
  (hugosym PLCG1)\
  (synonyms \"1-phosphatidylinositol-4,5-bisphosphate phosphodiesterase gamma 1\" \
            \"EC 3.1.4.11 \" \
            \"Phosphoinositide phospholipase C \" \
            \"PLC-gamma-1 \" \
            \"Phospholipase C-gamma-1 \" \
            \"PLC-II,  PLC-148, PLC1 \"))"] .
  op Plcg2 : -> Protein [metadata "(\
  (spname PIG2_HUMAN)\
  (spnumber P16885)\
  (hugosym PLCG2)\
  (synonyms \"1-phosphatidylinositol-4,5-bisphosphate phosphodiesterase gamma 2\" \
            \"EC 3.1.4.11 \" \
            \"Phosphoinositide phospholipase C \" \
            \"PLC-gamma-2 \" \
            \"Phospholipase C-gamma-2 \" \
            \"PLC-IV \"))"] .

op PP2a : -> Composite [metadata "((ssloc  )\
  (subunits Ppp2ca Ppp2cb Ppp2r1a Ppp2r1b Ppp2r1a Ppp2r1b Ppp2r2a Ppp2r2b \
            Ppp2r2c Ppp2r2d Ppp2r3a Ppp2r3b Ppp2r4 Ppp2r5a Ppp2r5b \
            Ppp2r5c Ppp2r5d Ppp2r5e)\
  (comment  \"Protein Phosphatase PP2A consists of:  \"\
            \"a 36 kDa catalytic subunit: Ppp2ca or Ppp2cb \"\
            \"a 65 kDa constant regulatory subunit: Ppp2r1a or Ppp2r1b \"\
            \"a variety of regulatory subunits which include: \"\
            \"regulatory subunits B: Ppp2r2 - Ppp2r5 \"\
            \"viral proteins, and cell signaling molecules. \"))"] .

op Raf1 : -> Protein [metadata "((ssloc  )\
  (spnumber P04049)\
  (hugosym RAF1)\
  (synonyms \"RAF proto-oncogene serine/threonine-protein kinase \"\
            \"Transforming replication defective murine retrovirus 3611-MSV \"\
            \"Raf-1, C-RAF, cRaf, RAF, Oncogene MIL \"\
            \"RAF1_HUMAN \"))"] .

op Shc : -> Protein [metadata "(\
  (spname SHC1_HUMAN)\
  (spnumber P29353)\
  (hugosym SHC1)\
  (synonyms \"SHC transforming protein 1 \" \
            \"SH2 domain protein C1 \" \
            \"Src homology 2 domain containing transforming protein C1 \" \
            \"SHC, SHCA \"))"] .

op Sos1  : -> Protein [metadata "(\
  (spname SOS1_HUMAN)\
  (spnumber Q07889)\
  (hugosym SOS1)\
  (synonyms \"Son of sevenless protein homolog 1, SOS-1 \" \
            \"SOS1 guanine nucleotide exchange factor \" \
            \"Son of sevenless, drosophila homolog 1  \"))"] .

op Src : -> Protein [metadata "(\
  (spname SRC_HUMAN)\
  (spnumber P12931)\
  (hugosym SRC)\
  (synonyms \"Proto-oncogene tyrosine-protein kinase Src \" \
            \"Avian sarcoma virus protein, ASV \" \
            \"Tyrosine kinase pp60c-src \" \
            \"Tyrosine protein kinase SRC-1 \" \
            \"Protooncogene SRC, Rous sarcoma \" \
            \"v-src sarcoma (Schmidt-Ruppin A-2) viral oncogene homolog \" \
            \"p60-Src, c-Src, SRC1 \"))"] .

op Tgfa   : -> ErbB1L 
  [metadata "((ssloc  )\
  (spnumber P01135)\
  (hugosym TGFA)\
  (synonyms \"Transforming growth factor alpha precursor \"\
            \"TGF-alpha \"\
            \"EGF-like TGF, ETGF \"\
            \"TGF type 1  \"\
            \"TGFA_HUMAN \"))"] .

op Ube2l3 : -> Protein [metadata "(\
  (spname UB2L3_HUMAN)\
  (spnumber P68036)\
  (hugosym UBE2L3)\
  (synonyms \"Ubiquitin-conjugating enzyme E2 L3 (EC 6.3.2.19) \" \
            \"Ubiquitin-protein ligase L3 \" \
            \"Ubiquitin carrier protein L3 \" \
            \"UbcH7, E2-F1, L-UBC, UBCE7, UBCH7 \"))"] .

op Vav2 : -> Protein [metadata "(\
  (spname VAV2_HUMAN)\
  (spnumber P52735)\
  (hugosym VAV2)\
  (synonyms \"Vav-2 protein.\"))"] .


endfm
