#!/usr/bin/perl
use warnings;
use strict;
# inplace editing with emacs style backups
$^I = "~";
@ARGV = (
	 "src/GUI/Constants.java",
	 "src/g2d/swing/IOPConstants.java"
	 );
my $version = undef;
foreach (`svn info`){
    if(/^Revision:\s+(\d+)/){
	$version = $1;
    }
}
while(<>){ 
    if(/public\s+static\s+final\s+int\s+versionNumber\s+ =\s+(\d+)/){
	s/$1/$version/g;
    }
    print;
}
