(seq 
    (load "../../PLALib/g2dlib.lsp")
    (sinvoke "g2d.util.ActorMsg" "send" "maude" "graphics2d" "OK") )

(seq 
    (apply defKBManagerD (array java.lang.String "rafUbe213Dish" "rasDish"  ))
    (sinvoke "g2d.util.ActorMsg" "send" "maude" "graphics2d" "OK") )

(seq 
    ( define evidencePath "" )
    (sinvoke "g2d.util.ActorMsg" "send" "maude" "graphics2d" "OK") )

(seq 
    ( seq ( define useChattyLabels ( boolean true ) ) )
    (sinvoke "g2d.util.ActorMsg" "send" "maude" "graphics2d" "OK") )

(seq 
    (apply defKBGraph "SmallKB" (array java.lang.String  "Cbl-CLc" "Cbl-Yphos-CLi" "Egf:EgfR-act-CLm" "Tgfa:EgfR-act-CLm" "Egf-Out" "EgfR-CLm" "Tgfa-Out" "Grb2-CLc" "Grb2-reloc-CLi" "PIP2-CLm" "DAG-CLm" "IP3-CLc" "Plcg-act-CLi" "PIP3-CLm" "Pi3k-act-CLi" "Pak1-CLc" "Pak1-act-CLi" "Pi3k-CLc" "Gab1-Yphos-CLi" "Sos1-CLc" "Sos1-reloc-CLi" "Gab1-CLc" "Shc-CLc" "Shc-Yphos-CLi" "Src-CLi" "Vav2-CLc" "Vav2-act-CLi" "Src:Cbl-Yphos:Vav2-act-CLi" "Ube2l3-ubiq-CLi" "Ube2l3-CLi" "Egf:EgfR-ubiq-CLm" "Tgfa:EgfR-ubiq-CLm" "Grb2-Yphos-CLi" "Plcg-CLc" "Hras-GDP-CLi" "Hras-GTP-CLi" "1433x1-CLc" "Raf1-CLc" "1433x1-CLi" "Raf1-act-CLi" "PP2a-CLc" )  (array java.lang.String  "0" "1" "2" "4" "6" "7" "9" "11" "12" "15" "16" "17" "18" "20" "21" "23" "24" "27" "28" "30" "31" "33" "36" "37" "38" "41" "42" "45" "47" "48" "49" "51" "53" "56" "59" "60" "62" "63" "64" "65" "66" ) (array java.lang.Object  (array java.lang.Object "base" "Cbl" "Protein") (array java.lang.Object "modified" (array java.lang.Object "base" "Cbl" "Protein")  (array java.lang.Object "mod" "Yphos")) (array java.lang.Object "complex"  (array java.lang.Object "base" "Egf" "ErbB1L") (array java.lang.Object "modified" (array java.lang.Object "base" "EgfR" "Protein")  (array java.lang.Object "mod" "act"))) (array java.lang.Object "complex"  (array java.lang.Object "base" "Tgfa" "ErbB1L") (array java.lang.Object "modified" (array java.lang.Object "base" "EgfR" "Protein")  (array java.lang.Object "mod" "act"))) (array java.lang.Object "base" "Egf" "ErbB1L") (array java.lang.Object "base" "EgfR" "Protein") (array java.lang.Object "base" "Tgfa" "ErbB1L") (array java.lang.Object "base" "Grb2" "Protein") (array java.lang.Object "modified" (array java.lang.Object "base" "Grb2" "Protein")  (array java.lang.Object "mod" "reloc")) (array java.lang.Object "base" "PIP2" "Chemical") (array java.lang.Object "base" "DAG" "Chemical") (array java.lang.Object "base" "IP3" "Chemical") (array java.lang.Object "modified" (array java.lang.Object "base" "Plcg" "Plc")  (array java.lang.Object "mod" "act")) (array java.lang.Object "base" "PIP3" "Chemical") (array java.lang.Object "modified" (array java.lang.Object "base" "Pi3k" "Composite")  (array java.lang.Object "mod" "act")) (array java.lang.Object "base" "Pak1" "Protein") (array java.lang.Object "modified" (array java.lang.Object "base" "Pak1" "Protein")  (array java.lang.Object "mod" "act")) (array java.lang.Object "base" "Pi3k" "Composite") (array java.lang.Object "modified" (array java.lang.Object "base" "Gab1" "Protein")  (array java.lang.Object "mod" "Yphos")) (array java.lang.Object "base" "Sos1" "Protein") (array java.lang.Object "modified" (array java.lang.Object "base" "Sos1" "Protein")  (array java.lang.Object "mod" "reloc")) (array java.lang.Object "base" "Gab1" "Protein") (array java.lang.Object "base" "Shc" "Protein") (array java.lang.Object "modified" (array java.lang.Object "base" "Shc" "Protein")  (array java.lang.Object "mod" "Yphos")) (array java.lang.Object "base" "Src" "Protein") (array java.lang.Object "base" "Vav2" "Protein") (array java.lang.Object "modified" (array java.lang.Object "base" "Vav2" "Protein")  (array java.lang.Object "mod" "act")) (array java.lang.Object "complex"  (array java.lang.Object "base" "Src" "Protein") (array java.lang.Object "modified" (array java.lang.Object "base" "Cbl" "Protein")  (array java.lang.Object "mod" "Yphos")) (array java.lang.Object "modified" (array java.lang.Object "base" "Vav2" "Protein")  (array java.lang.Object "mod" "act"))) (array java.lang.Object "modified" (array java.lang.Object "base" "Ube2l3" "Protein")  (array java.lang.Object "mod" "ubiq")) (array java.lang.Object "base" "Ube2l3" "Protein") (array java.lang.Object "complex"  (array java.lang.Object "base" "Egf" "ErbB1L") (array java.lang.Object "modified" (array java.lang.Object "base" "EgfR" "Protein")  (array java.lang.Object "mod" "ubiq"))) (array java.lang.Object "complex"  (array java.lang.Object "base" "Tgfa" "ErbB1L") (array java.lang.Object "modified" (array java.lang.Object "base" "EgfR" "Protein")  (array java.lang.Object "mod" "ubiq"))) (array java.lang.Object "modified" (array java.lang.Object "base" "Grb2" "Protein")  (array java.lang.Object "mod" "Yphos")) (array java.lang.Object "base" "Plcg" "Plc") (array java.lang.Object "modified" (array java.lang.Object "base" "Hras" "Protein")  (array java.lang.Object "mod" "GDP")) (array java.lang.Object "modified" (array java.lang.Object "base" "Hras" "Protein")  (array java.lang.Object "mod" "GTP")) (array java.lang.Object "base" "1433x1" "Protein") (array java.lang.Object "base" "Raf1" "Protein") (array java.lang.Object "base" "1433x1" "Protein") (array java.lang.Object "modified" (array java.lang.Object "base" "Raf1" "Protein")  (array java.lang.Object "mod" "act")) (array java.lang.Object "base" "PP2a" "Composite") ) (array java.lang.String  "CLc" "CLi" "CLm" "CLm" "Out" "CLm" "Out" "CLc" "CLi" "CLm" "CLm" "CLc" "CLi" "CLm" "CLi" "CLc" "CLi" "CLc" "CLi" "CLc" "CLi" "CLc" "CLc" "CLi" "CLi" "CLc" "CLi" "CLi" "CLi" "CLi" "CLm" "CLm" "CLi" "CLc" "CLi" "CLi" "CLc" "CLc" "CLi" "CLi" "CLc" ) (array java.lang.String  "15.Cbl.reloc.Yphos" "15.Cbl.reloc.Yphos#1" "1.EgfR.act" "1.EgfR.act#1" "5.Grb2.reloc" "5.Grb2.reloc#1" "7.IP3.from.PIP2.by.Plc" "9.PIP3.from.PIP2.by.Pi3k" "E56.Pak1.irt.Egf" "E56.Pak1.irt.Egf#1" "8.Pi3k.act" "13.Sos1.reloc" "4.Gab1.Yphosed" "4.Gab1.Yphosed#1" "11.Shc.Yphosed" "11.Shc.Yphosed#1" "14.Vav2.act" "14.Vav2.act#1" "clt1.ctest" "2.EgfR.ubiq" "2.EgfR.ubiq#1" "12.Sos1.reinit" "12.Sos1.reinit#1" "10.Plcg.act" "10.Plcg.act#1" "6.Hras.act.1" "280.Raf1.by.Hras" ) (array java.lang.String  "3" "5" "8" "10" "13" "14" "19" "22" "25" "26" "29" "32" "34" "35" "39" "40" "43" "44" "46" "50" "52" "54" "55" "57" "58" "61" "67" ))
    (sinvoke "g2d.util.ActorMsg" "send" "maude" "graphics2d" "OK") )

(seq 
    (let ((makeGraph (lambda (graph mouseClickedClosure)
        (seq
         (apply newOccNode graph mouseClickedClosure "6" "Egf" "Egf-Out" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "7" "EgfR" "EgfR-CLm" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "2" "Egf:EgfR-act" "Egf:EgfR-act-CLm" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "8" "1" "1.EgfR.act" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "6 7" "2") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "11" "Grb2" "Grb2-CLc" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "12" "Grb2-reloc" "Grb2-reloc-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "13" "5" "5.Grb2.reloc" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "11 2" "12 2") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "30" "Sos1" "Sos1-CLc" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "31" "Sos1-reloc" "Sos1-reloc-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "32" "13" "13.Sos1.reloc" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "30 12" "31 12") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "33" "Gab1" "Gab1-CLc" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "28" "Gab1-Yphos" "Gab1-Yphos-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "34" "4" "4.Gab1.Yphosed" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "33 2 12" "28 2 12") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "53" "Grb2-Yphos" "Grb2-Yphos-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "54" "12" "12.Sos1.reinit" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "12 31 2" "30 53 2") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "27" "Pi3k" "Pi3k-CLc" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "21" "Pi3k-act" "Pi3k-act-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "29" "8" "8.Pi3k.act" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "27 28" "21 28") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "15" "PIP2" "PIP2-CLm" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "20" "PIP3" "PIP3-CLm" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "22" "9" "9.PIP3.from.PIP2.by.Pi3k" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "15 21" "20 21") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "56" "Plcg" "Plcg-CLc" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "18" "Plcg-act" "Plcg-act-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "38" "Src" "Src-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "57" "10" "10.Plcg.act" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "56 20 38 2" "18 20 38 2") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "59" "Hras-GDP" "Hras-GDP-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "true" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "60" "Hras-GTP" "Hras-GTP-CLi" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "61" "6" "6.Hras.act.1" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "59 20 12 31" "60 20 12 31") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "16" "DAG" "DAG-CLm" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newOccNode graph mouseClickedClosure "17" "IP3" "IP3-CLc" (array java.lang.String  "init" "status") (array java.lang.String  "" "none") colorPnetNode)
(apply newRuleNode graph mouseClickedClosure "19" "7" "7.IP3.from.PIP2.by.Plc" (array java.lang.String  "status" "pre" "post") (array java.lang.String  "none" "15 18" "16 17 18") colorPnetNode)

         (apply newEdge graph "6" "8" "false")
(apply newEdge graph "7" "8" "false")
(apply newEdge graph "8" "2" "false")
(apply newEdge graph "11" "13" "false")
(apply newEdge graph "13" "12" "false")
(apply newEdge graph "2" "13" "true")
(apply newEdge graph "30" "32" "false")
(apply newEdge graph "32" "31" "false")
(apply newEdge graph "12" "32" "true")
(apply newEdge graph "33" "34" "false")
(apply newEdge graph "34" "28" "false")
(apply newEdge graph "2" "34" "true")
(apply newEdge graph "12" "34" "true")
(apply newEdge graph "12" "54" "false")
(apply newEdge graph "31" "54" "false")
(apply newEdge graph "54" "30" "false")
(apply newEdge graph "54" "53" "false")
(apply newEdge graph "2" "54" "true")
(apply newEdge graph "27" "29" "false")
(apply newEdge graph "29" "21" "false")
(apply newEdge graph "28" "29" "true")
(apply newEdge graph "15" "22" "false")
(apply newEdge graph "22" "20" "false")
(apply newEdge graph "21" "22" "true")
(apply newEdge graph "56" "57" "false")
(apply newEdge graph "57" "18" "false")
(apply newEdge graph "20" "57" "true")
(apply newEdge graph "38" "57" "true")
(apply newEdge graph "2" "57" "true")
(apply newEdge graph "59" "61" "false")
(apply newEdge graph "61" "60" "false")
(apply newEdge graph "20" "61" "true")
(apply newEdge graph "12" "61" "true")
(apply newEdge graph "31" "61" "true")
(apply newEdge graph "15" "19" "false")
(apply newEdge graph "19" "16" "false")
(apply newEdge graph "19" "17" "false")
(apply newEdge graph "18" "19" "true")

      )))
        (graph (object ("g2d.graph.IOPGraph")))
        (mouseClickedClosure 
          (if (boolean true) 
             (apply mkPnetMouseClickedClosure graph)
          (if (boolean false) 
             (apply mkXnetMouseClickedClosure graph)
             (object null)
          )) ))
   (seq
     (apply makeGraph graph mouseClickedClosure)
     (invoke graph "setUID" "graph2")
     (apply setAttrsAV graph (array java.lang.String  "kbname" "unRchGoals" "source" "subtitle") (array java.lang.String  "SmallKB" "" "pnet pnet1" "") (int 4) (int 0))
     (setAttr graph "colorFun" colorPnetNode)
     graph
   )
 )
    (sinvoke "g2d.util.ActorMsg" "send" "maude" "graphics2d" "OK") )