#!/bin/bash

if [ -z $1 ];
then
    echo "We need the coverity token: e.g. "
    echo  "./coverity-submit tHiSiSnOtMyKeY"
    exit 1
else
   COVERITY_TOKEN=$1
fi

rm iopc.tgz
tar czvf iopc.tgz cov-int
curl --form token=${COVERITY_TOKEN} \
  --form email=iam@csl.sri.com \
  --form file=@iopc.tgz \
  --form version="Current  Stable" \
  --form description="Interoperability Framework" \
  https://scan.coverity.com/builds?project=SRI-CSL%2Fiopc
