#!/bin/bash

JLAMBDAJAR=jlambda.jar

: ${IOPBINDIR?"Need to set IOPBINDIR (where iop.jar and jlambda.jar live)!"}

IOP="${IOPBINDIR}"

#echo "Using ${IOP} to locate classes!"         

JLPATH=""

if [ -n  "$JLAMBDA_CLASSES" ]
then
    #echo "Using ${JLAMBDA_CLASSES} to augment classes!" 
    JLPATH=":${JLAMBDA_CLASSES}"
fi

CMD="java  -Dcom.apple.mrj.application.apple.menu.about.name=jlambda -Xms256m -Xmx1024m  -ea -cp ${IOP}/${JLAMBDAJAR}${JLPATH}  g2d/jlambda/ReadEvalPrintLoop ${IOP}"

if [ $1 ]; then 
    $CMD $1
else
    $CMD
fi

