#!/usr/bin/perl -w
use warnings;

if(!defined($ENV{IOPBINDIR})){
    print "You must set envionment variable IOPBINDIR!\n";
} else {

    my $iop = "$ENV{IOPBINDIR}/bin";

    if($ARGV[0]){
	system "java -ea -cp ${iop} g2d/jlambda/ReadEvalPrintLoop $ARGV[0]";
    } else {
	system "java -ea  -cp ${iop} g2d/jlambda/ReadEvalPrintLoop";
    }
}
