#!/usr/bin/perl
use warnings;

my $jlambdaClasses = "";
if(defined($ENV{JLAMBDA_CLASSES})){
    $jlambdaClasses = ":$ENV{JLAMBDA_CLASSES}";
}

if(!defined($ENV{IOPBINDIR})){
    print "You must set envionment variable IOPBINDIR!\n";
} else {
    my $iop = "$ENV{IOPBINDIR}";
    if($ARGV[0]){
	system "java  -Xms256m -Xmx1024m  -ea -cp ${iop}/iop.jar${jlambdaClasses}  g2d/jlambda/ReadEvalPrintLoop $iop $ARGV[0]";
    } else {
	system "java  -Xms256m -Xmx1024m -ea  -cp ${iop}/iop.jar${jlambdaClasses}  g2d/jlambda/ReadEvalPrintLoop $iop";
    }
}
