#!/usr/bin/perl
use warnings;
use strict;

if(!defined($ENV{IOPBINDIR})){
    print "You must set envionment variable IOPBINDIR!\n";
} else {
    my $iop = "$ENV{IOPBINDIR}"; #/bin";
    my $maude = `which maude.linux`;
    if(!$maude){
	print "Could not find maude.linux, exiting\n";
	die; 
    }
    $maude =~ m|(.*)/maude\.linux$|;
    $maude = $1;

    #print "iop_main @ARGV $iop $maude\n";

    system("iop_main @ARGV $iop $maude");
}
