#!/usr/bin/perl
use warnings;
use strict;


if(!defined($ENV{IOPBINDIR})){
    print "You must set envionment variable IOPBINDIR!\n";
} else {
    my $iop = "$ENV{IOPBINDIR}/bin";
    my $maude = `which maude.darwin`;
    if(!$maude){
	print "Could not find maude.darwin, exiting\n";
	die; 
    }
    $maude =~ m|(.*)/maude\.darwin$|;
    $maude = $1;

    system("iop_main @ARGV $iop $maude");
}
