#!/usr/bin/perl
use strict;
use warnings;

use Proc::ProcessTable;


my  $t = new Proc::ProcessTable;
my $iop_main_pid = 0;

foreach my $p ( @{$t->table} ){
    if($p->cmndline =~ /^iop_main /){
	$iop_main_pid = $p->pid;
    }
}

if($iop_main_pid){
    kill HUP => $iop_main_pid;
    print STDOUT "Sent $iop_main_pid the HUP signal!\n";
} else {
    print STDOUT "Didn't see iop_main.\n";
}

