#!/usr/bin/perl
use warnings;
use strict;
use File::Spec;
my $exe  = $ARGV[0];
my $path = $ENV{PATH};
if(!defined($exe)){
    die "Usage: ${0} <filename>\n";
}
if(!defined($path)){
    die "Your PATH is not set, I know not whither ${exe} lies!\n";
}
my ($found, $location) = &whither($exe);
if($found){
    if(-d $location){
	print "dir = ${location}\n";
    } else {
	my ($dir, $file) = &cdDotDot($location);
	print "dir = ${dir}  exe = ${file}\n";
    }
}
sub whither {
    my $exe  = $_[0];
    my @PATH = File::Spec->path();
    foreach my $node (@PATH){
	my $file = &resolve($exe, $node);
	if(defined($file)){
	    if(-l $file){ 
		my $link = readlink($file);
		my ($base) = &cdDotDot($file);
		if(File::Spec->file_name_is_absolute($link)){
		    return (1, $link);
		} else {
		    return (1,  &blend($base, $link));
		}
	    } else {
		return (1, $file);
	    }
	    last;
	} 
    }
    return (0, undef);
}
sub resolve {
    my ($exe, $node) = @_;
    if(-d $node){
	my $handle;
	opendir($handle, $node) || die "Couldn't opendir ${node}: $!\n";
	while(my $file = readdir($handle)){
	    if($file =~ /^${exe}$/){
		return File::Spec->catfile($node, $file);
	    }
	}
	closedir($handle);
    }
    return undef;
}
sub cdDotDot {
    my $file = $_[0];
    if(${file} =~ m|(.*/)([^/]+?)/?$|){
	return ($1, $2); 
    }  else {
	return ($file, undef);
    } 
}
sub blend {
    my ($base, $link) = @_;
    while($link =~ m|^\.\./(.*)$|){
	$link = $1;
	($base) = &cdDotDot($base);
    }
    return File::Spec->catfile($base, $link);
}
